<?php

/**
 * PluginecManufacturer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginecManufacturer extends BaseecManufacturer {
  const FOLDER_NAME = 'marcas';

  /**
   * Devuelve el path absoluto de la imagen
   * 
   * @return string
   */
  public function getPath() {
    return sfConfig::get('sf_upload_dir') . '/' . self::FOLDER_NAME . '/' . $this->getImage();
  }

  /**
   * Devuelve la ruta a partir de /uploads
   * 
   * @return string
   */
  public function getSrc() {
    return '/' . self::FOLDER_NAME . '/' . $this->getImage();
  }

}