<?php

/**
 * PluginmdOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdOrderTable extends chamanDoctrineTable {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdOrderTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdOrder');
  }
  
  public function addOrderRelationsColumn(Doctrine_Query $q) {
    $q->leftJoin($q->getRootAlias() . '.mdCliente c')
      ->leftJoin($q->getRootAlias() . '.mdOrderState s')
      ->leftJoin('s.Translation t')
      ->orderBy($q->getRootAlias() . '.id DESC');
    return $q;
  }
}