<?php

/**
 * PluginecProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginecProductTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginecProductTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginecProduct');
  }

  public function addTranslation(Doctrine_Query $q) {
    $q->leftJoin($q->getRootAlias() . '.Translation t');
    return $q;
  }

}