<?php

/**
 * PluginmdDiscountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdDiscountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdDiscountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdDiscount');
    }
}