<?php

/**
 * PluginmdOrderDiscountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdOrderDiscountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdOrderDiscountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdOrderDiscount');
    }
}