<?php

/**
 * PluginmdCartTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdCartTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdCartTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdCart');
    }
}