<?php

/**
 * PluginmdOrderDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdOrderDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdOrderDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdOrderDetail');
    }
}