<?php

/**
 * PluginmdProductSaleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdProductSaleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdProductSaleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdProductSale');
    }
}