<?php

/**
 * PluginmdAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdAddressTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdAddress');
    }
}