<?php

/**
 * PluginmdOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdOrder extends BasemdOrder
{
  protected $customer = null;
  // Se agrega este metodo porque no se declaro como clave foranea
  public function getMdOrderProducts()
  {
    return Doctrine::getTable('mdOrderDetail')->findBy('md_order_id', $this->getId());
  }
  
  // Se agrega este metodo porque no se declaro como clave foranea
  public function getMdCart()
  {
    return Doctrine::getTable('mdCart')->find($this->getMdCartId());
  }
  
  public function getQuantity(){
    $orderItems = $this->getMdOrderProducts();
    
    if(!$orderItems) return 0;

    $qty = 0;
    foreach($orderItems as $orderItem){
      $qty+= $orderItem->getItemQuantity();
    }
    
    return $qty;
  }
  
  public function getSubTotal(){
    $orderItems = $this->getMdOrderProducts();
    
    if(!$orderItems) return 0;

    $total = 0;
    foreach($orderItems as $orderItem){
      $total+= $orderItem->getTotal($orderItem->getItemQuantity());
    }
    
    return $total;
  }
  
  public function getTotal(){
    // costo productos + costo envio
    $total = $this->getSubTotal() + $this->getTotalShipping();  
    
    return $total;
  }  
  
  public function getDisplayTotal(){
    return Tools::displayPrice((float)$this->getTotal());
  }  
  
  public function getDisplaySubTotal(){
    return Tools::displayPrice((float)$this->getSubTotal());
  }
  
  public function getDisplayTotalShipping(){
    return Tools::displayPrice((float)$this->getTotalShipping());
  }   
  
  // Tuve que hacer este getter porque en el schema no lo defini como clave foranea
  public function getShippingData(){
    return Doctrine::getTable('mdAddress')->find($this->getAddressDeliveryId());
  }
  
  public function isOrderValid(){

    if(sfContext::getInstance()->getUser()->isAuthenticated())
    {
      return ($this->getCustomerId() == sfContext::getInstance()->getUser()->getGuardUser()->getId());
    }
    else
    {
      return false;
    }

  }
  
  /**
   * Setea la orden para ser revisada y setea el estado de la orden
   */
  public function callToReview($status = NULL){
    // Enviar Mail al Admin
    // TODO
    
    $this->setToReview(true);
    $this->save();
    
    if(!is_null($status))
    {
      $mdOrderHistory = new mdOrderHistory();
      $mdOrderHistory->setMdOrderId($this->getId());
      $mdOrderHistory->setMdOrderStateId($status);
      $mdOrderHistory->save();
    }
  }
  
  /**
   * Setea la orden como cancelada
   */
  public function callCanceled($status = NULL){    
    $mdOrderHistory = new mdOrderHistory();
    $mdOrderHistory->setMdOrderId($this->getId());
    $mdOrderHistory->setMdOrderStateId(sfConfig::get('app_configuration_MD_CANCELED'));
    $mdOrderHistory->save();
  }  

  public function getmdCurrency(){
    return mdCurrencyTable::getInstance()->find($this->getCurrencyId());
  }

  public function getCustomer(){
    if($this->customer == null)
      $this->customer = sfGuarduserTable::getInstance()->find($this->getCustomerId());

    return $this->customer;
  }


  /**
   * Envia un mail al usuario con los datos del metodo de pago
   * 
   */
  public function sendCustomerMail()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers(array('I18N', 'Partial'));
    
    $from_email = sfConfig::get('app_configuration_MD_SALE_FROM');
    $from_name = sfConfig::get('app_configuration_MD_SALE_NAME');

    $to_email = $this->getCustomer()->getEmail();

    $partial = get_partial('mdCart/resume_mail', array('mdOrder' => $this));

    $options = array();
    $options['sender']    = array('name' => $from_name, 'email' => $from_email);
    $options['body']      = $partial;
    $options['subject']   = __("mdEcommerce_subject resume");
    $options['recipients'] = $to_email;

    // MAIL AL CLIENTE
    return mdMailHandler::sendMail($options);

  }


  /**
   * Envia un mail al admin de la compra
   * 
   */
  public function sendAdminMail()
  {
    sfContext::getInstance()->getConfiguration()->loadHelpers(array('I18N', 'Partial'));

    $from_email = $this->getCustomer()->getEmail();
    $from_name = $this->getCustomer()->getName();
    
    $to_email = sfConfig::get('app_configuration_MD_SALE_FROM');


    $partial = get_partial('mdCart/resume_mail_admin', array('mdOrder' => $this));

    $options = array();
    $options['sender']    = array('name' => $from_name, 'email' => $from_email);
    $options['body']      = $partial;
    $options['subject']   = __("mdEcommerce_subject resume");
    $options['recipients'] = $to_email;    

    // MAIL AL ADMIN
    return mdMailHandler::sendMail($options);
  }

}