<?php

/**
 * PluginmdOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdOrder');
    }
}