<?php

/**
 * PluginmdCartDiscountTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdCartDiscountTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdCartDiscountTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdCartDiscount');
    }
}