<?php

/**
 * PluginecBrouTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginecBrouTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginecBrouTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginecBrou');
  }

  public function getLastRegister($md_order_id){
    return Doctrine::getTable('ecBrou')->createQuery('a')
      ->where('a.md_order_id = ?', $md_order_id)
      ->orderBy('a.id DESC')
      ->limit(1)
      ->fetchOne();
  }  
}