<?php

/**
 * PluginecProductToCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginecProductToCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginecProductToCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginecProductToCategory');
    }
}