<?php

/**
 * PluginmdOrderHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdOrderHistoryTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdOrderHistoryTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdOrderHistory');
  }
  
  public function findHistories($md_order_id){
    return Doctrine_Core::getTable('mdOrderHistory')
      ->createQuery('h')
      ->leftJoin('h.mdOrderState s')
      ->leftJoin('s.Translation t')
      ->where('h.md_order_id = ?', $md_order_id)
      ->orderBy('h.id DESC')
      ->execute();
  }

}