<?php

/**
 * PluginmdDeliveryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdDeliveryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdDeliveryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdDelivery');
    }
}