<?php

/**
 * PluginecManufacturerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginecManufacturerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginecManufacturerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginecManufacturer');
    }
}