<?php

/**
 * PluginmdPaypal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdPaypal extends BasemdPaypal
{
  public static $status = array('canceled' => 'canceled', 'rejected' => 'rejected', 'pending' => 'pending', 'payed' => 'payed');
  
  public static function create($md_order_id)
  {
    $register =  new mdPaypal();
    $register->setMdOrderId($md_order_id);
    $register->setMethod('Express Checkout');
    $register->setStatus(self::$status['pending']);
    $register->save();
    return $register;
  }
}