<?php

/**
 * PluginmdCurrencyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdCurrencyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdCurrencyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdCurrency');
    }
}