<?php

/**
 * PluginmdCarrierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdCarrierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdCarrierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdCarrier');
    }
}