<?php

/**
 * PluginecAbitabTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginecAbitabTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginecAbitabTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginecAbitab');
  }
  
  public function getLastRegister($md_order_id){
    return Doctrine::getTable('ecAbitab')->createQuery('a')
      ->where('a.md_order_id = ?', $md_order_id)
      ->orderBy('a.id DESC')
      ->limit(1)
      ->fetchOne();
  }

}