<?php

/**
 * PluginmdOrderDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdOrderDetail extends BasemdOrderDetail
{
  public function getDisplayPrice() {
    return Tools::displayPrice((float) $this->getItemPrice());
  }

  public function getTotal($qty) {
    return (float) $this->getItemPrice() * (int) ($qty);
  }

  public function getDisplayTotal($qty) {
    return Tools::displayPrice((float) $this->getTotal($qty));
  }
  
  public function getSlug() {
    return mdBasicFunction::slugify($this->getItemName());
  }
  
  public function getEcProduct(){
    return Doctrine::getTable('ecProduct')->find($this->getItemId());
  }
}