<?php

/**
 * PluginmdOrderStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdOrderStateTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdOrderStateTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdOrderState');
  }
  
  public function findAllStatus(){
    return Doctrine_Core::getTable('mdOrderState')
      ->createQuery('s')
      ->leftJoin('s.Translation t')
      ->execute();
  }

}