<?php

/**
 * PluginecRedPagosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginecRedPagosTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginecRedPagosTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginecRedPagos');
  }
  
  public function getLastRegister($md_order_id){
    return Doctrine::getTable('ecRedPagos')->createQuery('a')
      ->where('a.md_order_id = ?', $md_order_id)
      ->orderBy('a.id DESC')
      ->limit(1)
      ->fetchOne();
  }  

}