<?php

/**
 * PluginmdOrderHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdOrderHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdOrderHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdOrderHistory');
    }
}