<?php

/**
 * PluginmdCarrier
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdCarrier extends BasemdCarrier
{
  // Los valores de estas constantes deben coincidir con los ids de la tabla md_carrier
  const FREE_CARRIER = 1;
  
  const MY_CARRIER = 2;
  
  // TODO Refactor this method
  public function getTotal()
  {
    if(!$this->getIsFree())
    {
      $mdDelivery = Doctrine::getTable('mdDelivery')->findOneByMdCarrierId($this->getId());
      return $mdDelivery->getPrice();
    }
    
    return 0;
  }
}
