<?php

/**
 * PluginecProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginecProduct extends BaseecProduct {

  private $categorias_ids = NULL;

  public function getObjectClass() {
    return get_class($this);
  }

  public function hasCategory($id) {

    if (is_null($this->categorias_ids)) {
      $this->categorias_ids = array();
      $records = $this->getEcCategories();
      foreach ($records as $record) {
        $this->categorias_ids[] = $record['id'];
      }
    }

    return in_array($id, $this->categorias_ids);
  }

  public function getDisplayPrice($precision = 2) {
    return Tools::md_round((float)$this->getPrice(), $precision);
  }
  
  public function isInStock($qty){
    return (int)$this->getQuantity() > (int)$qty;
  }

}