<?php

/**
 * PluginmdCartProductsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdCartProductsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdCartProductsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdCartProducts');
    }
}