<?php

/**
 * PluginmdPaymentModuleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdPaymentModuleTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object PluginmdPaymentModuleTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('PluginmdPaymentModule');
  }

  public function findActiveModules() {
    return Doctrine_Core::getTable('mdPaymentModule')
      ->createQuery('p')
      ->leftJoin('p.Translation t')
      ->where('p.active = ?', '1')
      ->execute();
  }
  
}