<?php

/**
 * PluginmdCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdCart extends BasemdCart
{
  const COOKIE_CART_NAME = '__MD_CAR';
  
  public function orderExists(){
    return false;
  }
  
  public function getTotal() {
    return '120.00 USD';
    //return ($this->total * (1 + $this->tax_percentage / 100)) + $this->selectedQuoteAmount - $this->coupondiscount;
  }
  
  public function getQuantity(){
    return 10;
  }
}