<?php

/**
 * PluginmdCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginmdCurrency extends BasemdCurrency
{
  const COOKIE_CURRENCY_NAME = '__MD_CUR';
  
  public static $currency = NULL;
  
  public static function storageCurrency($currency_id) {
    
    if (is_numeric($currency_id)) {
      $currency = Doctrine::getTable('mdCurrency')->find($currency_id);
      if ($currency && $currency->getActive()){
        sfContext::getInstance()->getResponse()->setCookie(mdCurrency::COOKIE_CURRENCY_NAME, $currency_id, time() + (15 * 24 * 3600));
      }
    }
    
  }
  
  public static function loadCurrency(){
    
    if(!is_null(self::$currency))
      return self::$currency;
    
    $cookie_currency_id = sfContext::getInstance()->getRequest()->getCookie(mdCurrency::COOKIE_CURRENCY_NAME);
    
    if ((int) $cookie_currency_id) {
      $currency = Doctrine::getTable('mdCurrency')->find($cookie_currency_id);
      if ($currency && $currency->getActive()){
        self::$currency = $currency;
        return $currency;
      }
    }

    $currency_id = sfConfig::get('app_configuration_MD_CURRENCY_DEFAULT');
    
    $currency = Doctrine::getTable('mdCurrency')->find($currency_id);
    
    if ($currency && $currency->getActive()){
      
      self::$currency = $currency;
      self::storageCurrency($currency->getId());
      return $currency;
      
    }else{
      
      throw new Exception('Configuration Currency FAIL. Check app.yml to configure the default value and check the table mdCurrency of the database');
      
    }

  }

}
