generator:
  class: sfDoctrineGenerator
  param:
    model_class:           mdOrder
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          md_order
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        customer: { label: Usuario }
        customer_id: { label: Usuario }        
        total_products: { label: Precio }
        module_payment: { label: Forma de Pago }
        md_order_state: { label: Estado }
        md_order_state_id: { label: Estado }
        to_review: { label: Revisar }
        created_at: { label: Fecha, date_format: dd/MM/yyyy }
      list:
        # 3 querys listado        
        # 2 querys for _customer
        display: [=id, _customer, _total_products, module_payment, md_order_state, to_review, created_at] 
        table_method: addOrderRelationsColumn
        object_actions:
          detail:
            label: ver
            action: detail
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
