# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/09-Cache

_destacados:
  enabled:    true
  lifetime:   86400
  
_recientes:
  enabled:    true
  lifetime:   86400  
  