######### BACKEND ##########

ec_manufacturer:
  class: sfDoctrineRouteCollection
  options:
    model:                ecManufacturer
    module:               marcasBackend
    prefix_path:          /marcas
    column:               id
    with_wildcard_routes: true

ec_product:
  class: sfDoctrineRouteCollection
  options:
    model:                ecProduct
    module:               productosBackend
    prefix_path:          /productos
    column:               id
    with_wildcard_routes: true

ec_category:
  class: sfDoctrineRouteCollection
  options:
    model:                ecCategory
    module:               categoriasBackend
    prefix_path:          /categorias
    column:               id
    with_wildcard_routes: true

ec_category_associate:
  url: /category/associate
  param: { module: categoriasBackend, action: associate }

ec_category_subtree:
  url:   /category/tree
  param: { module: categoriasBackend, action: tree }
  
md_order:
  class: sfDoctrineRouteCollection
  options:
    model:                mdOrder
    module:               pedidosBackend
    prefix_path:          /pedidosBackend
    column:               id
    with_wildcard_routes: true  
###########################


######### FRONTEND ##########
mdCart-init:
  url:   /mdcart/init
  param: { module: mdCart, action: initCart }
  
mdCart-add:
  url:   /mdcart/add
  param: { module: mdCart, action: addCart }
  
mdCart-update:
  url:   /mdcart/update
  param: { module: mdCart, action: updateCart }
  
mdCart-remove:
  url:   /mdcart/remove
  param: { module: mdCart, action: removeCart }

mdCart-clear:
  url:   /mdcart/clear
  param: { module: mdCart, action: clearCart }
  
mdCart-display:
  url:   /mdcart/display
  param: { module: mdCart, action: displayCart }
  
mdCart-checkout:
  url:   /mdcart/checkout
  param: { module: mdCart, action: checkoutCart }
  
mdCart-cart:
  url:   /mdcart/cart
  param: { module: mdCart, action: cart }

mdCart-payment:
  url:   /mdcart/payment
  param: { module: mdCartPayment, action: paymentCart }
  
mdCart-finish:
  url:   /mdcart/finish
  param: { module: mdCart, action: paymentFinish }
###########################

########mdCartAddress######
mdCartAddress-new:
  url:   /mdcartaddress/new
  param: { module: mdCartAddress, action: new }

mdCartAddress-edit:
  url:   /mdcartaddress/edit
  param: { module: mdCartAddress, action: edit }

mdCartAddress-create:
  url:   /mdcartaddress/create
  param: { module: mdCartAddress, action: create }

mdCartAddress-update:
  url:   /mdcartaddress/update
  param: { module: mdCartAddress, action: update }
  
mdCartAddress-validate:
  url:   /mdcartaddress/validate
  param: { module: mdCartAddress, action: validate }
###########################

#########Routing para los metodos de pago#############
payment-abitab:
  url:   /abitab/validate/:c
  param: { module: abitab, action: validate }
  
payment-redpagos:
  url:   /redpagos/validate/:c
  param: { module: redpagos, action: validate }

payment-brou:
  url:   /brou/validate/:c
  param: { module: brou, action: validate }
  
process-abitab:
  url:   /abitab/process
  param: { module: abitab, action: process }
  
process-redpagos:
  url:   /redpagos/process
  param: { module: redpagos, action: process }

process-brou:
  url:   /brou/process
  param: { module: brou, action: process }
  
process-cashondelivery:
  url:   /cashondelivery/process
  param: { module: cashondelivery, action: process }
  
process-cashinstore:
  url:   /cashinstore/process
  param: { module: cashinstore, action: process }  
  
mdPaypalReturnUrl:
  url:   /paypal/validate
  param: { module: paypal, action: validate }

mdPaypalCancelUrl:
  url:   /paypal/cancel
  param: { module: paypal, action: cancel }
######################################################