generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ecProduct
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ec_product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        code: { label: Codigo }
        name: { label: Nombre }
        number: { label: Numero de producto }
        copete: { label: Copete }
        description: { label: Descripcion }
        quantity: { label: Cantidad }
        model: { label: Modelo }
        price: { label: Precio }
        display_price: { label: Precio }
        price_offer: { label: Precio de Oferta }
        show_price: { label: Mostrar Precio }        
        active: { label: Activo }
        status: { label: Cuando no hay stock }
        out_of_stock: { label: Stock }
        in_offer: { label: En Oferta }
        highlight: { label: Destacado }
        conditions: { label: Estado }
        width: { label: Ancho }
        height: { label: Alto }
        depth: { label: Profundidad }
        weight: { label: Peso }
        ec_manufacturer_id: { label: Marcas }
        ec_providers_list: { label: Proveedores }
        ec_categories_list: { label: Categorias }        
      list:
        #display: [=id, =name, display_price, quantity, _active, _out_of_stock, _in_offer]
        display: [=id, =name, display_price]
        table_method: addTranslation
      filter:
        display: [name , code, active, highlight, in_offer, ec_categories_list]
      form:    ~
      edit:    ~
      new:     ~
