generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ecManufacturer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ec_manufacturer
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: Nombre }
        image: { label: Imagen }
      list:
        display: [_image, name ]
        sort: [name, asc]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
