ecCategory:
  actAs:
    I18n:
      fields: [name]
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    name:
      type: string(255)
    position:
      type: integer

############ TODO ############
# Se podria agregar: 
#   una realacion a una categoria por defecto id_category_default
#   `wholesale_price` decimal(20,6) NOT NULL DEFAULT '0.000000',
#   `additional_shipping_cost` decimal(20,2) NOT NULL DEFAULT '0.00',

ecProduct:
  actAs:
    Timestampable: ~
    mdI18nBehavior: ~
<?php if( sfConfig::get( 'sf_plugins_shopping_media', false ) ):  ?>
    mdMediaBehavior: ~
<?php endif; ?>
    I18n:
        fields: [name, copete, description]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    copete:
      type: text
    description:
      type: text
    quantity:
      type: integer(4)
      default: 0
      notnull: true
    price:
      type: decimal(20,6)
      default: '0.000000'
      notnull: true
    price_offer:
      type: decimal(20,6)
      default: '0.000000'
      notnull: true
    ## Medidas del paquete  ##
    width:
      type: float
      default: 0
      notnull: true
    height:
      type: float
      default: 0
      notnull: true
    depth:
      type: float
      default: 0
      notnull: true
    weight:
      type: float
      default: 0
      notnull: true 
    #######################  
    active:
      type: boolean
      default: true
    #Cuando no hay stock:
    # Denegar pedidos: 0
    # Admitir pedidos: 1
    # Por defecto: Denegar pedidos (marcar como Preferencias)      
    status:
      type: boolean
      default: false
    in_offer:
      type: boolean
      default: false
    show_price:
      type: boolean
      default: true
    conditions:
      type: enum
      values: [new, used, refurbished]
      notnull: true
      default: new
    viewed:
      type: integer
      default: 0
    ec_manufacturer_id:
      type: integer(4)
  relations:
    ecManufacturer:
      foreignType: one
    ecProviders:
      class: ecProvider
      refClass: ecProductToProvider
      local: ec_product_id
      foreign: ec_provider_id
    ecCategories:
      class: ecCategory
      refClass: ecProductToCategory
      local: ec_product_id
      foreign: ec_category_id

ecProductToCategory:
  options:
    symfony:
      form:   false
      filter: false
  columns:
    ec_product_id:
      type: integer(4)
      primary: true
    ec_category_id:
      type: integer(5)
      primary: true
  relations:
    ecProduct:
      local: ec_product_id
      onDelete: CASCADE
    ecCategory:
      local: ec_category_id
      onDelete: CASCADE

ecManufacturer:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    image:
      type: string(255)
      notnull: false

### USUARIO ###
# id_address 	id_country 	id_state 	id_customer 	id_manufacturer 	id_supplier 	alias 	company 	lastname 	
# firstname 	address1 	address2 	postcode 	city 	other 	phone 	phone_mobile 	vat_number 	dni 	
# date_add 	date_upd 	active 	deleted

mdAddress:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    carrier_id:  
      type: integer(4)    
    currency_id:
      type: integer(4)      
      notnull: true
    customer_id:
      type: integer(4)
      notnull: true
    country_id:
      type: integer(4)
      notnull: true
    alias:
      type: string(32)
    lastname:
      type: string(32)
      notnull: true
    firstname:
      type: string(32)
      notnull: true      
    address1:
      type: string(128)
      notnull: true    
    address2:
      type: string(128)
    postcode:
      type: string(16)
    city:
      type: string(64)
    phone:
      type: string(16)
    phone_mobile:
      type: string(16)
    other:
      type: text
    dni:
      type: string(16)
    active: 
      type: boolean
      notnull: true
###############

### CARRITO ###
# TODO:
# RELACIONES
mdCart:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    carrier_id:
      type: integer(4)      
    currency_id:
      type: integer(4)      
      notnull: true
    customer_id:
      type: integer(4)
    address_delivery_id:
      type: integer(4)
    discount_id:
      type: integer(4)
    lang:
      type: string(2)
      notnull: true
  
# TODO
# Se puede generalizar a cualquier tipo de objeto vendible, para ello
# cambiariamos ec_product_id por el par: object_id, object_class
#
mdCartProducts:
  options:
    symfony:
      form:   false
      filter: false  
  actAs:
    Timestampable: ~
  columns:
    md_cart_id:
      type: integer(4)
      primary: true      
    ec_product_id:
      type: integer(4)
      notnull: true
      primary: true
    quantity:
      type: integer
      default: 0
      notnull: true
  relations:
    ecProduct:
      local: ec_product_id
      onDelete: CASCADE
    mdCart:
      local: md_cart_id
      onDelete: CASCADE

###############

mdDiscount:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
    type:
      type: integer
      notnull: true
    customer_id:
      type: integer(4)
      notnull: true
    currency_id:
      type: string(32)
      notnull: true
    name:
      type: string(32)
      notnull: true
    value:
      type: decimal(17,2)
      notnull: true
    date_from:
      type: timestamp
      notnull: true
    date_to:
      type: timestamp
      notnull: true
    active:
      type: boolean
      notnull: true
      default: true

### OREDENES ###
# TODO
# RELACIONES
#
mdOrder:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    md_cart_id:
      type: integer(4)
    carrier_id:  
      type: integer(4)      
    currency_id:
      type: integer(4)      
      notnull: true
    customer_id:
      type: integer(4)
      notnull: true
    address_delivery_id:
      type: integer(4)
    md_discount_id:
      type: integer(4)
    module_payment:
      type: string(255)
      notnull: true      
    lang:
      type: string(2)
      notnull: true
    secure_key:
      type: string(32)
    conversion_rate:
      type: decimal(13,6)
      notnull: true
      default: 1.000000
    total_discounts:
      type: decimal(17,2)
      notnull: true
      default: 0.00
    total_shipping:
      type: decimal(17,2)
      notnull: true
      default: 0.00
    total_products:
      type: decimal(17,2)
      notnull: true
      default: 0.00
    delivery_date:
      type: timestamp
      notnull: true
      
# TODO: RELACIONES
#
mdOrderDetail:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    md_order_id:
      type: integer(4)
      notnull: true
    item_id:
      type: integer(4)
    item_name:
      type: string(255)
      notnull: true
    item_quantity:
      type: integer(4)
      notnull: true
    item_price:
      type: decimal(20,6)
      default: 0.000000
      notnull: true
    item_weight:
      type: float

mdCurrency:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(32)
      notnull: true
    iso_code:
      type: string(3)
      notnull: true
    iso_code_num:
      type: string(3)
      notnull: true
    sign:
      type: string(8)
      notnull: true
    blank:
      type: integer(1)
      default: 0
      notnull: true
      unsigned: true
    format:
      type: integer(1)
      default: 0
      notnull: true
      unsigned: true      
    decimals:
      type: integer(1)
      default: 1
      notnull: true
      unsigned: true      
    conversion_rate:
      type: decimal(13,6)
      default: 0.000000
      notnull: true
    active:
      type: boolean
      default: true

# TODO: RELACIONES
#
mdOrderHistory:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    md_order_id:
      type: integer(4)
      notnull: true
    md_order_state:
      type: integer(4)
      notnull: true

mdOrderState:
  actAs:
    mdI18nBehavior: ~
    I18n:
        fields: [name, copete, description]  
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(64)
      notnull: true

# NOT IMPLEMENTED YET #
# mdTax:
# ################### #

###############

#mdOrderState
#1-En espera de pago por cheque 	cheque
#2-Pago aceptamos 	payment
#3-Preparación en curso 	preparation
#4-Enviado 	shipped
#5-Entregado 	 
#6-Cancelada 	order_canceled
#7-Reembolsado 	refund
#8-Error de pago 	payment_error
#9-Productos fuera de línea 	outofstock
#10-En espera de pago por transferencia bancaria 	bankwire
#11-En espera de pago por PayPal 	 
#12-Payment remotely accepted 	 
#13-Authorization accepted from PayPal